### PR TITLE
Proposal: Add cmdline tools

### PR DESCRIPTION
**Pull request by maxmeyer**
This PR will introduce a commandline tool for generating patterns. Interested? Can be handy for testing. :-) But it is not finished yes. Base on all my other PRs...

### CODE REVIEW

**Comment by jasonlong** [comment]
@maxmeyer The more I think about it, the more I feel like your idea of a separate `geo_pattern-cli` tool might be better here. It would keep things simpler here and would the cli version would seem like a good place for experimentation.

**Comment by maxmeyer** [comment]
Would you mind to create the repository?

**Comment by jasonlong** [comment]
:boom: You got it. Added you as a collaborator as well.

**Comment by jasonlong** [comment]
Closing this out for now.

**Comment by maxmeyer** [comment]
Thanks.

**Pull request closed without merging**
