### PR TITLE
Change api for GeoPattern.generate

### PR DESCRIPTION
**Pull request by maxmeyer**
As discussed in #47 this will improve the api.

### CODE REVIEW

**Comment by maxmeyer** [comment]
@jasonlong 

I changed the api in the readme. Can you have a look at it? Is this api ok for you?

**Comment by jasonlong** [comment]
Let me chew on this a little. This still feels a little off to me and I think it's important to make this as clear as possible.

**Comment by jasonlong** [comment]
Hey @maxmeyer, so I'm leaning towards letting things settle here for a while. We've made a lot of changes recently and I'd like to make sure the library is solid for people before continuing to change it. I also haven't had much time to focus on this recently and I'd like to think through the future direction here a bit before doing much more.

I'm going to close this for now, but let's revisit down the road.

**Comment by maxmeyer** [comment]
Ok. Send me a ping. :smile:

**Comment by maxmeyer** [comment]
http://www.rubyflow.com/p/adzgl2-a-new-release-for-geopattern-is-available

**Comment by jasonlong** [comment]
Nice writeup @maxmeyer!

**Comment by maxmeyer** [comment]
Thanks :smile:

**Pull request closed without merging**
