### PR TITLE
Install all of the gems for the test script

### PR DESCRIPTION
**Pull request by tarebyte**
This deal with #48 when you run the test script you are only install the rake gem. Which is why the CI is failing.

### CODE REVIEW

**Comment by tarebyte** [comment]
The tests are working, rubocop is complaining about offenses 😄

**Comment by tarebyte** [comment]
@jasonlong if you want I can fix them in this PR, it seems a little out of scope though

**Comment by maxmeyer** [comment]
The bundle install is done via rake. So rake needs to be installed.

**Comment by tarebyte** [comment]
Alrighty then

**Comment by maxmeyer** [comment]
Fixed by #50

**Comment by maxmeyer** [comment]
Thought using rake would be a good idea to have everything at one place :smile:.

**Pull request closed without merging**
