### PR TITLE
Rubocop fixes

### PR DESCRIPTION
**Pull request by jasonlong**
Ran `rubocop -a`

### CODE REVIEW

**Comment by jasonlong** [comment]
@tarebyte I'm doing some annual rubocop housekeeping here and have run into some aruba errors that are over my head. Are these things pretty easy to fix up? If it's more than a couple of minutes, please don't bother - I'm not too worried about it.

**Comment by tarebyte** [comment]
@jasonlong I think it works be making the following change:

```diff
diff --git a/spec/support/aruba.rb b/spec/support/aruba.rb
index d86b159..1b003d5 100644
--- a/spec/support/aruba.rb
+++ b/spec/support/aruba.rb
@@ -1,25 +1,3 @@
 # frozen_string_literal: true
 
-require 'aruba/api'
-require 'aruba/reporting'
-
-# Spec Helpers
-module SpecHelper
-  # Helpers for aruba
-  module Aruba
-    include ::Aruba::Api
-
-    def dirs
-      @dirs ||= %w[tmp rspec]
-    end
-  end
-end
-
-RSpec.configure do |c|
-  c.include SpecHelper::Aruba
-
-  c.before :each do
-    setup_aruba
-    restore_env
-  end
-end
+require 'aruba/rspec'
```

Looks like everything that support file was doing is now [included as part of 1.0](https://app.cucumber.pro/p/af1681aa-415f-44f0-8260-5454a69c472a/aruba/documents/release/Version%201.0.0/features/03_testing_frameworks/rspec/setup_aruba_for_rspec.feature)

If that doesn't look right I'd just lock the Gemfile to `gem 'aruba', '~> 0.14.14'`

**Comment by jasonlong** [comment]
Thanks @tarebyte :bow:. That did the trick for the aruba errors. Now it looks like I have to fix ~90 frozen string literal errors. 🙈

**Comment by nogweii** [comment]
Closing this since the other PR (#75) covers this as well.

**Pull request closed without merging**
